name: process_run_test
description: Process run example and tests
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  process_run: '>=1.0.0+3'
  args:
  path:
  pub_semver:
  test:
dev_dependencies:
  lints: '>=4.0.0'


dependency_overrides:
  process_run:
    path: ../process_run
