name: Run CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.dart }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: packages/process_run
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dart: [3.0.5, stable, beta, dev]
    steps:
      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: ${{ matrix.dart }}
      - uses: actions/checkout@v4
      - run: dart --version
      - run: dart pub get
      - run: dart run tool/run_ci.dart